/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.microbasuralesapp;

/**
 *
 * @author luza1
 */
public class MenuBasurero extends javax.swing.JFrame {

    /**
     * Creates new form MenuBasurero
     */
    public MenuBasurero() {
        initComponents();
    }
    Basurero newBasurero=new Basurero();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPopupMenu popmenuBuscar = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CrearBasurero = new javax.swing.JButton();
        BuscaCaller = new javax.swing.JButton();
        BuscarTipo = new javax.swing.JButton();
        Lista = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        popBuscarCalle = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        CalleBuscar = new javax.swing.JTextField();
        AceptBuscar = new javax.swing.JButton();
        popBuscarTipo = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        TipoBuscar = new javax.swing.JTextField();
        AceptBuscarTipo = new javax.swing.JButton();
        popBuscarTipo1 = new javax.swing.JInternalFrame();
        jLabel5 = new javax.swing.JLabel();
        TipoBuscar1 = new javax.swing.JTextField();
        AceptBuscarTipo1 = new javax.swing.JButton();
        popBuscarTipo2 = new javax.swing.JInternalFrame();
        jLabel6 = new javax.swing.JLabel();
        TipoBuscar2 = new javax.swing.JTextField();
        AceptBuscarTipo2 = new javax.swing.JButton();
        popBuscarTipo3 = new javax.swing.JInternalFrame();
        jLabel7 = new javax.swing.JLabel();
        TipoBuscar3 = new javax.swing.JTextField();
        AceptBuscarTipo3 = new javax.swing.JButton();
        popEliminar = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        IdEliminar = new javax.swing.JTextField();
        AceptEliminar = new javax.swing.JButton();
        popCrear = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        latitudB = new javax.swing.JTextField();
        longitudB = new javax.swing.JTextField();
        numCalleB = new javax.swing.JTextField();
        calleB = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        popmenuBuscar.setInvoker(AceptBuscar);
        popmenuBuscar.setMaximumSize(new java.awt.Dimension(30, 30));
        popmenuBuscar.setName("popBuscar"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(500, 800));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setText("Eliga una opcion :)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 35));

        CrearBasurero.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        CrearBasurero.setText("Crear Basurero");
        CrearBasurero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearBasurero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearBasureroActionPerformed(evt);
            }
        });
        jPanel1.add(CrearBasurero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, 20));

        BuscaCaller.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        BuscaCaller.setText("Buscar por calle");
        BuscaCaller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BuscaCaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaCallerActionPerformed(evt);
            }
        });
        jPanel1.add(BuscaCaller, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 160, -1));

        BuscarTipo.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        BuscarTipo.setText("Buscar por tipo");
        BuscarTipo.setToolTipText("");
        BuscarTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BuscarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTipoActionPerformed(evt);
            }
        });
        jPanel1.add(BuscarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 160, -1));

        Lista.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        Lista.setText("Mostrar Lista Basurero");
        Lista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaActionPerformed(evt);
            }
        });
        jPanel1.add(Lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 160, -1));

        Eliminar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        Eliminar.setText("Eliminar Basurero");
        Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 160, -1));

        Volver.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        Volver.setText("Volver");
        Volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        jPanel1.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 70, -1));

        popBuscarCalle.setClosable(true);
        popBuscarCalle.setVisible(false);
        popBuscarCalle.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel2.setText("Ingrese la Calle");
        popBuscarCalle.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 90, -1));

        CalleBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalleBuscarActionPerformed(evt);
            }
        });
        popBuscarCalle.getContentPane().add(CalleBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 80, -1));

        AceptBuscar.setText("Aceptar");
        AceptBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptBuscarActionPerformed(evt);
            }
        });
        popBuscarCalle.getContentPane().add(AceptBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 80, -1));

        jPanel1.add(popBuscarCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 250, 160));

        popBuscarTipo.setClosable(true);
        popBuscarTipo.setVisible(false);
        popBuscarTipo.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel3.setText("Ingrese el tipo de basurero");
        popBuscarTipo.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 150, -1));

        TipoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoBuscarActionPerformed(evt);
            }
        });
        popBuscarTipo.getContentPane().add(TipoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 80, -1));

        AceptBuscarTipo.setText("Aceptar");
        AceptBuscarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptBuscarTipoActionPerformed(evt);
            }
        });
        popBuscarTipo.getContentPane().add(AceptBuscarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 80, -1));

        popBuscarTipo1.setClosable(true);
        popBuscarTipo1.setVisible(true);
        popBuscarTipo1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel5.setText("Ingrese el tipo de basurero");
        popBuscarTipo1.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 150, -1));

        TipoBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoBuscar1ActionPerformed(evt);
            }
        });
        popBuscarTipo1.getContentPane().add(TipoBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 80, -1));

        AceptBuscarTipo1.setText("Aceptar");
        AceptBuscarTipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptBuscarTipo1ActionPerformed(evt);
            }
        });
        popBuscarTipo1.getContentPane().add(AceptBuscarTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 80, -1));

        popBuscarTipo.getContentPane().add(popBuscarTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 250, 160));

        popBuscarTipo2.setClosable(true);
        popBuscarTipo2.setVisible(true);
        popBuscarTipo2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel6.setText("Ingrese el tipo de basurero");
        popBuscarTipo2.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 150, -1));

        TipoBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoBuscar2ActionPerformed(evt);
            }
        });
        popBuscarTipo2.getContentPane().add(TipoBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 80, -1));

        AceptBuscarTipo2.setText("Aceptar");
        AceptBuscarTipo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptBuscarTipo2ActionPerformed(evt);
            }
        });
        popBuscarTipo2.getContentPane().add(AceptBuscarTipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 80, -1));

        popBuscarTipo3.setClosable(true);
        popBuscarTipo3.setVisible(true);
        popBuscarTipo3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel7.setText("Ingrese el tipo de basurero");
        popBuscarTipo3.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 150, -1));

        TipoBuscar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoBuscar3ActionPerformed(evt);
            }
        });
        popBuscarTipo3.getContentPane().add(TipoBuscar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 80, -1));

        AceptBuscarTipo3.setText("Aceptar");
        AceptBuscarTipo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptBuscarTipo3ActionPerformed(evt);
            }
        });
        popBuscarTipo3.getContentPane().add(AceptBuscarTipo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 80, -1));

        popBuscarTipo2.getContentPane().add(popBuscarTipo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 250, 160));

        popBuscarTipo.getContentPane().add(popBuscarTipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 250, 160));

        jPanel1.add(popBuscarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 250, 160));

        popEliminar.setClosable(true);
        popEliminar.setVisible(false);
        popEliminar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Ingrese la Calle");
        popEliminar.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 90, -1));

        IdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdEliminarActionPerformed(evt);
            }
        });
        popEliminar.getContentPane().add(IdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 80, -1));

        AceptEliminar.setText("Aceptar");
        AceptEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptEliminarActionPerformed(evt);
            }
        });
        popEliminar.getContentPane().add(AceptEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 80, -1));

        jPanel1.add(popEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 250, 160));

        popCrear.setClosable(true);
        popCrear.setVisible(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        latitudB.setText("00.00000000");
        latitudB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latitudBActionPerformed(evt);
            }
        });
        jPanel2.add(latitudB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, -1));

        longitudB.setText("00.00000000");
        longitudB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longitudBActionPerformed(evt);
            }
        });
        jPanel2.add(longitudB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, -1));

        numCalleB.setText("Numero de la calle");
        jPanel2.add(numCalleB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 140, -1));

        calleB.setText("Nombre de la calle");
        jPanel2.add(calleB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel8.setText("Ingrese los datos del basurero");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Pila", "Plastico", "Papel", "Vidrio", "Organico", "Metal" }));
        jComboBox1.setToolTipText("");
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        javax.swing.GroupLayout popCrearLayout = new javax.swing.GroupLayout(popCrear.getContentPane());
        popCrear.getContentPane().setLayout(popCrearLayout);
        popCrearLayout.setHorizontalGroup(
            popCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );
        popCrearLayout.setVerticalGroup(
            popCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        );

        jPanel1.add(popCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 360, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptEliminarActionPerformed
        // TODO add your handling code here:
        newBasurero.Eliminar(Long.parseLong(IdEliminar.getText()));
    }//GEN-LAST:event_AceptEliminarActionPerformed

    private void IdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdEliminarActionPerformed

    private void AceptBuscarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptBuscarTipoActionPerformed
        // TODO add your handling code here:
        newBasurero.BuscarCalle(TipoBuscar.getText());
    }//GEN-LAST:event_AceptBuscarTipoActionPerformed

    private void TipoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoBuscarActionPerformed

    private void AceptBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptBuscarActionPerformed
        // TODO add your handling code here:
        newBasurero.BuscarCalle(CalleBuscar.getText());
    }//GEN-LAST:event_AceptBuscarActionPerformed

    private void CalleBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalleBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalleBuscarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        popEliminar.setVisible(true);
    }//GEN-LAST:event_EliminarActionPerformed

    private void ListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaActionPerformed
        // TODO add your handling code here:
        newBasurero.MostrarLista();
    }//GEN-LAST:event_ListaActionPerformed

    private void BuscarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTipoActionPerformed
        // TODO add your handling code here:
        popBuscarTipo.setVisible(true);
    }//GEN-LAST:event_BuscarTipoActionPerformed

    private void BuscaCallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaCallerActionPerformed
        // TODO add your handling code here:
        popBuscarCalle.setVisible(true);
    }//GEN-LAST:event_BuscaCallerActionPerformed

    private void CrearBasureroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearBasureroActionPerformed
        
        popCrear.setVisible(true);
        
    }//GEN-LAST:event_CrearBasureroActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);
        
    }//GEN-LAST:event_VolverActionPerformed

    private void TipoBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoBuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoBuscar1ActionPerformed

    private void AceptBuscarTipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptBuscarTipo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AceptBuscarTipo1ActionPerformed

    private void TipoBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoBuscar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoBuscar2ActionPerformed

    private void AceptBuscarTipo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptBuscarTipo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AceptBuscarTipo2ActionPerformed

    private void TipoBuscar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoBuscar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoBuscar3ActionPerformed

    private void AceptBuscarTipo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptBuscarTipo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AceptBuscarTipo3ActionPerformed

    private void latitudBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latitudBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latitudBActionPerformed

    private void longitudBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longitudBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_longitudBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBasurero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBasurero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBasurero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBasurero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBasurero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptBuscar;
    private javax.swing.JButton AceptBuscarTipo;
    private javax.swing.JButton AceptBuscarTipo1;
    private javax.swing.JButton AceptBuscarTipo2;
    private javax.swing.JButton AceptBuscarTipo3;
    private javax.swing.JButton AceptEliminar;
    private javax.swing.JButton BuscaCaller;
    private javax.swing.JButton BuscarTipo;
    private javax.swing.JTextField CalleBuscar;
    private javax.swing.JButton CrearBasurero;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField IdEliminar;
    private javax.swing.JButton Lista;
    private javax.swing.JTextField TipoBuscar;
    private javax.swing.JTextField TipoBuscar1;
    private javax.swing.JTextField TipoBuscar2;
    private javax.swing.JTextField TipoBuscar3;
    private javax.swing.JButton Volver;
    private javax.swing.JTextField calleB;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField latitudB;
    private javax.swing.JTextField longitudB;
    private javax.swing.JTextField numCalleB;
    private javax.swing.JInternalFrame popBuscarCalle;
    private javax.swing.JInternalFrame popBuscarTipo;
    private javax.swing.JInternalFrame popBuscarTipo1;
    private javax.swing.JInternalFrame popBuscarTipo2;
    private javax.swing.JInternalFrame popBuscarTipo3;
    private javax.swing.JInternalFrame popCrear;
    private javax.swing.JInternalFrame popEliminar;
    // End of variables declaration//GEN-END:variables
}
